name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Cargo Stylus
        run: cargo install --force cargo-stylus cargo-stylus-check

      - name: Run Cargo plugin
        run: cargo stylus check
