name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Cargo Stylus
        run: cargo install --force cargo-stylus --version 0.5.3

      - name: Install Cargo Stylus Check
        run: cargo install --force cargo-stylus-check --version 0.4.2

      - name: Deploy the contract seabrick NFT
        working-directory: ./seabrick-nft
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: cargo stylus deploy --private-key=$PRIVATE_KEY

      - name: Deploy the contract seabrick Market
        working-directory: ./seabrick-market
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: cargo stylus deploy --private-key=$PRIVATE_KEY
