name: linux
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: (${{ matrix.target }}, ${{ matrix.cfg_release_channel }})
    env:
      CFG_RELEASE_CHANNEL: ${{ matrix.cfg_release_channel }}
    strategy:
      matrix:
        target: [wasm32-unknown-unknown]
        cfg_release_channel: [nightly, stable]

    steps:
      - name: checkout
        uses: actions/checkout@v3

        # Run build
      - name: install rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
          sh rustup-init.sh -y --default-toolchain none
          rustup target add ${{ matrix.target }}

      - name: Build and Test - NFT
        run: ./ci/build.sh --path ./seabrick-nft/

      - name: Build and Test - Market
        run: ./ci/build.sh --path ./seabrick-market/

      - name: Build and Test - Ownership
        run: ./ci/build.sh --path ./ownership/
